# Generated by Django 5.1.7 on 2025-03-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('lyrics', models.TextField()),
                ('mood_tags', models.CharField(help_text='Comma-separated mood tags (e.g., happy, sad, relaxed)', max_length=200)),
                ('full_audio', models.FileField(blank=True, null=True, upload_to='full_songs/')),
                ('preview_file', models.FileField(blank=True, null=True, upload_to='previews/')),
            ],
        ),
    ]
